services:
  # Base de datos
  db:
    container_name: ${APP_NAME}-database
    image: ${DB_PROVIDER}
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./persistence/bd:/docker-entrypoint-initdb.d/:ro
    networks:
      net:
        ipv4_address: 172.21.1.2

  # Servidor Web (Apache/PHP)
  www:
    container_name: ${APP_NAME}-www
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    links:
      - db:${DB_PROVIDER}
    volumes:
      - ${APP_DIR}:/var/www/html:cached
    ports:
      - ${HTTP_PORT}:80
    networks:
      net:
        ipv4_address: 172.21.1.3


networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24